In [1]:
import numpy as np

In [3]:
#Creating a numpy vector
vector=np.array([2,3,4,7])

#vector into a 2x2 matrix
matrix = vector.reshape(2,2)

#Calculating the determinant
determinant = np.linalg.det(matrix)
print(vector)
print(matrix)
print (determinant)

[2 3 4 7]
[[2 3]
 [4 7]]
2.0


In [4]:

a = np.array([[1,2],[3,4]])
print("Original array:")
print(a)
result =  np.linalg.det(a)
print("Determinant of the said array:")

Original array:
[[1 2]
 [3 4]]
Determinant of the said array:


In [5]:
vector = np.array([6, 8, 3, 2, 9])
result = np.sqrt(vector)
print(result)

[2.44948974 2.82842712 1.73205081 1.41421356 3.        ]


In [9]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
result =  np.linalg.det(a)
print(result)

[[1 2]
 [3 4]]
-2.0000000000000004


In [1]:
#Scalar multiplication
scalar = 5
matrix = [[1,2,3],[4,5,6],[7,8,9]]
result = [[scalar element for element in row]row in matrix]
for row in result:
    print(row)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3422891888.py, line 4)

REFERENCES
https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-11.php
https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html